name: Upload Dataset Kaggle
on:
  push:
    branches:
      - main

jobs:
  upload_data_kaggle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install kaggle

      - name: Create .kaggle directory
        run: mkdir -p /home/runner/.kaggle

      - name: Set up Kaggle credentials
        run: echo "$KAGGLE_JSON" > /home/runner/.kaggle/kaggle.json && chmod 600 /home/runner/.kaggle/kaggle.json
        env:
          KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}

      - name: Update data in Kaggle
        run: kaggle datasets version -p ../dataset/. -m "Updated data"
        
      - name: Save dependency cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
