name: Upload Dataset Kaggle
on:
  push:
    branches:
      - main

jobs:
  upload_data_kaggle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Kaggle
        run: pip install kaggle

      - name: Install Pandas
        run: pip install pandas

      - name: Install BeautifulSoup
        run: pip install beautifulsoup

      - name: Install Selenium
        run: pip install selenium

      - name: Create .kaggle directory
        run: mkdir -p /home/runner/.kaggle

      - name: Set up Kaggle credentials
        run: echo "$KAGGLE_JSON" > /home/runner/.kaggle/kaggle.json && chmod 600 /home/runner/.kaggle/kaggle.json
        env:
          KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}

      - name: Scrapping data from EloRatings.Net
        run: python scripts/elo_scrapping.py

      - name: Update data in Kaggle
        run: kaggle datasets version -p ./dataset/. -m "Updated data"
